---
title: "Forcats"
description: |
  A short description of the post.
author:
  - name: "Ardalan Mirshani"
    url: "https://example.com/norajones"
# preview: https://www.jfkairport.com/static/JFK/image/jfk_taxi_new.jpg
date: 2020-12-03
tech: [["Python"]]
packages: [Matplotlib]
categories: [Visualization]
base_url: https://datamotto.com
output: 
  DataMotto::Dotto:
    self_contained: false
    md_extensions: -autolink_bare_uris
preview: "https://bookdown.org/kdonovan125/ibis_data_analysis_r4/_main_files/figure-html/ggplot_ex_4_1-2.png"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<li class="nav-item">
<a class="nav-link dm-dot-title">Report</a>
<div class="dm-dot-content">

Write your `Dotto` Here

```{r, echo = T, eval=F}
# heloo world
getwd()
library(ggplot2)
theme_set(theme_bw())  # pre-set the bw theme.
data("midwest", package = "ggplot2")
# midwest <- read.csv("http://goo.gl/G1K41K")  # bkup data source

# Scatterplot
gg <- ggplot(midwest, aes(x=area, y=poptotal)) + 
  geom_point(aes(col=state, size=popdensity)) + 
  geom_smooth(method="loess", se=F) + 
  xlim(c(0, 0.1)) + 
  ylim(c(0, 500000)) + 
  labs(subtitle="Area Vs Population", 
       y="Population", 
       x="Area", 
       title="Scatterplot", 
       caption = "Source: midwest")

plot(gg)
```
</div>
</li>

<li class="nav-item">
<a class="nav-link dm-dot-title">Summary</a>
<div class="dm-dot-content">
```{r, echo = F, out.width="30%"}
plot(1:3, 1:3)
```
</div>
</li>
