---
title: "My Forcats"
description: |
  A short description of the post.
author:
  - name: "Ardalan Mirshani"
    url: "https://mirshani.com"
date: 2020-12-03
techs:
  - lang: R
    pkg: ggplot2
    icon: '<i class="fab fa-r-project"></i>'
  - lang: Python
    pkg: matplotlib
    icon: '<i class="fab fa-python"></i>'
tech: [Python, R]
packages: [Matplotlib, ggplot2]
categories: [Visualization, Modeling]
preview: "https://bookdown.org/kdonovan125/ibis_data_analysis_r4/_main_files/figure-html/ggplot_ex_4_1-2.png"
cover_image_url: "https://bookdown.org/kdonovan125/ibis_data_analysis_r4/_main_files/figure-html/ggplot_ex_4_1-2.png"
output: DataMotto::Dotto
---

```{r datamotto_dotto, echo=FALSE}
DataMotto::use_dotto()
```

<!-------------------------------------------------->

```{r, mygg, Dot_title = "R", Dot_active = TRUE}
library(dplyr)
library(ggplot2)
theme_set(theme_bw())  # pre-set the bw theme.
data("midwest", package = "ggplot2")
# midwest <- read.csv("http://goo.gl/G1K41K")  # bkup data source

# Scatterplot
gg <- ggplot(midwest, aes(x=area, y=poptotal)) + 
  geom_point(aes(col=state, size=popdensity)) + 
  geom_smooth(method="loess", se=F) + 
  xlim(c(0, 0.1)) + 
  ylim(c(0, 500000)) + 
  labs(subtitle="Area Vs Population", 
       y="Population", 
       x="Area", 
       title="Scatterplot", 
       caption = "Source: midwest")

plot(gg)
```

<!-------------------------------------------------->

```{python, mypy, echo=T, Dot_title = "Python"}
import matplotlib.pyplot as plt
import numpy as np
t = 1 + np.arange(0, 2, 0.01)
s = 1 + np.sin(2*np.pi*t)
plt.plot(t,s)
plt.show()
```

<!-------------------------------------------------->

```{julia, myjulia, echo=T, Dot_title = "Julia"}
using Plots
x = 1:10; y = rand(10); # These are the plotting data
plot(x, y)
```

<!-------------------------------------------------->

```{r, init-sql, include=FALSE, Dot_open = F, Dot_clode = F}
library(DBI)
db = DBI::dbConnect(RSQLite::SQLite(), dbname = ":memory:")
dbWriteTable(db, "mtcars", mtcars)
```

```{sql, mysql, connection = db, echo=T, Dot_title = "SQL"}
SELECT * FROM mtcars
```

<!-------------------------------------------------->

```{node, mynode, echo=T, Dot_title = "node"}
console.log(1 + 2 + 3)
```

<!-------------------------------------------------->

```{r, init-myRcpp, echo = T, Dot_color = "Rcpp", Dot_title = "Rcpp", Dot_close=F}
library(Rcpp)
```

```{Rcpp, myrcpp, eval=T, echo = T, Dot_open = F, Dot_close = F}
#include <Rcpp.h>

// [[Rcpp::export]]
int timesTwo(int x) {
  return x * 2;
}
```

## Hello `Rcpp`!

```{r, echo = F, Dot_open = F}
timesTwo(5)
```

<!-------------------------------------------------->

```{r setup, Dot_title = "d3", Dot_color = "d3", Dot_close = F}
library(r2d3)
bars <- c(10, 20, 30)
```

```{d3 data=bars, options=list(color = 'orange'), Dot_open = F}
svg.selectAll('rect')
  .data(data)
  .enter()
    .append('rect')
      .attr('width', function(d) { return d * 10; })
      .attr('height', '20px')
      .attr('y', function(d, i) { return i * 22; })
      .attr('fill', options.color);
```

<!-------------------------------------------------->
