---
title: "Simple Data Visualization"
description: |
  We've broken the chart types into three broad categories to help with this.
author:
  - name: "Mohammad Hossein Malekpour"
    occupation: "Data Scientist"
    affiliation: "DataMotto"
    url: "https://www.linkedin.com/in/mohammadhossein-malekpour/"
    img: "MalekpourAvatar.jpg"
    lang: ["python", "R"]
tech:
  - lang: r
    pkgs: ["ggplot2", "dplyr"]
  - lang: python
    pkgs: ["seaborn", "pandas"]
date:
  created: "2021-06-22"
  last_updated: "2021-06-22"
categories: "Visualizer"
applications: "Other"
cover_image: NULL
slug: "simple-data-visualization"
output: DataMotto::Dotto
---

```{r DataMotto, echo=FALSE}
DataMotto::use_Dotto()

```

<!-- Dot 1, lang: r, python ------------------------------------------------>

```{block, Dot = 1, part = "Instruction", lang = "r"}
[ggplot2](https://ggplot2.tidyverse.org/) is a system for declaratively creating graphics, based on [The Grammar of Graphics](https://www.amazon.com/Grammar-Graphics-Statistics-Computing/dp/0387245448/ref=as_li_ss_tl). You provide the data, tell ggplot2 how to map variables to aesthetics, what graphical primitives to use, and it takes care of the details.

Since it's not always easy to decide how to best tell the story behind your data, we've broken the chart types into three broad categories to help with this.

- **Trends:** A trend is defined as a pattern of change.
  - `geom_line`
- **Relationship:** Understand relationships between variables in your data.
  - `geom_bar`
  - `geom_tile`
  - `geom_point`
  - `geom_smooth`
- **Distribution:** We visualize distributions to show the possible values that we can expect to see in a variable, along with how likely they are.
  - `geom_histogram`
  - `geom_density`
  - `geom_vline`

```

```{block, Dot = 1, part = "Instruction", lang = "python"}
[seaborn](https://seaborn.pydata.org/index.html#) is a Python data visualization library based on [matplotlib](https://matplotlib.org/). It provides a high-level interface for drawing attractive and informative statistical graphics.

Since it's not always easy to decide how to best tell the story behind your data, we've broken the chart types into three broad categories to help with this.

- **Trends:** A trend is defined as a pattern of change.
  - `sns.lineplot`
- **Relationship:** Understand relationships between variables in your data.
  - `sns.barplot`
  - `sns.heatmap`
  - `sns.scatterplot`
  - `sns.regplot`
  - `sns.lmplot`
  - `sns.swarmplot`
- **Distribution:** We visualize distributions to show the possible values that we can expect to see in a variable, along with how likely they are.
  - `sns.histplot`
  - `sns.kdeplot`
  - `sns.jointplot`

```

```{r, Dot = 1, part = "Code", echo = T, eval = F }
# There are a few lines of code that you'll need to run at the top of every notebook to set up your coding environment.
library(readr)   # Read tabular data.
library(dplyr)   # General data frame manipulation.
library(ggplot2) # Flexible plotting.


# Path of the file to read
auto_filepath <- "data/Automobile_data.csv"

# Read the file into a variable Automobile_data.csv
# The dataset consist of data From 1985 Ward's Automotive Yearbook.
auto <- read.csv(auto_filepath)

# Print the five random rows of the data
sample_n(auto, 5)

```

```{python, Dot = 1, part = "Code", echo = T, eval = F }
# There are a few lines of code that you'll need to run at the top of every notebook to set up your coding environment.
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
import seaborn as sns

# Path of the file to read
auto_filepath = "data/Automobile_data.csv"

# Read the file into a variable Automobile_data.csv
# The dataset consist of data From 1985 Ward's Automotive Yearbook.
auto = pd.read_csv(auto_filepath)

# Print the five random rows of the data
auto.sample(5)

```

```{r, Dot = 1, part = "Result", echo = F, eval = T}
# There are a few lines of code that you'll need to run at the top of every notebook to set up your coding environment.
library(readr)   # Read tabular data.
library(dplyr)   # General data frame manipulation.
library(ggplot2) # Flexible plotting.


# Path of the file to read
auto_filepath <- "data/Automobile_data.csv"

# Read the file into a variable Automobile_data.csv
# The dataset consist of data From 1985 Ward's Automotive Yearbook.
auto <- read.csv(auto_filepath)

# Print the five random rows of the data
sample_n(auto, 5)

```

```{python, Dot = 1, part = "Result", echo = F, eval = T}
# There are a few lines of code that you'll need to run at the top of every notebook to set up your coding environment.
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
import seaborn as sns

# Path of the file to read
auto_filepath = "data/Automobile_data.csv"

# Read the file into a variable Automobile_data.csv
auto = pd.read_csv(auto_filepath)

# Print the five random rows of the data
auto.sample(5)

```


<!-- Dot 2, lang: r, python ------------------------------------------------>

```{block, Dot = 2, part = "Instruction", lang = "r"}
**Line charts** are best to show trends over a period of time, and multiple lines can be used to show trends in more than one group. `geom_path()` connects the observations in the order in which they appear in the data. `geom_line()` connects them in order of the variable on the x axis. `geom_step()` creates a stairstep plot, highlighting exactly when changes occur. The `group` aesthetic determines which cases are connected together. Check the [documentation](https://ggplot2.tidyverse.org/reference/geom_path.html) for more details.

```

```{block, Dot = 2, part = "Instruction", lang = "python"}
`sns.lineplot` - **Line charts** are best to show trends over a period of time, and multiple lines can be used to show trends in more than one group. The relationship between x and y can be shown for different subsets of the data using the `hue`, `size`, and `style` parameters. Check the [documentation](https://seaborn.pydata.org/generated/seaborn.lineplot.html) for more details.

```

```{r, Dot = 2, part = "Code", echo = T, eval = F }
# Group variable will produce lines with different colors
ggplot(data = auto, aes(x = wheel.base, y = engine.size)) +
  geom_line(aes(group = fuel.type,
                color = fuel.type))

```

```{python, Dot = 2, part = "Code", echo = T, eval = F }
# Group variable using "hue" that will produce lines with different colors
sns.lineplot(data=auto, x="wheel-base", y="engine-size", hue="fuel-type")

```

```{r, Dot = 2, part = "Result", echo = F, eval = T}
# Group variable will produce lines with different colors
ggplot(data = auto, aes(x = wheel.base, y = engine.size)) +
  geom_line(aes(group = fuel.type,
                color = fuel.type))

```

```{python, Dot = 2, part = "Result", echo = F, eval = T}

# Group variable using "hue" that will produce lines with different colors
sns.lineplot(data=auto, x="wheel-base", y="engine-size", hue="fuel-type")

```


<!-- Dot 3, lang: r, python ------------------------------------------------>

```{block, Dot = 3, part = "Instruction", lang = "r"}
**Bar charts** are useful for comparing quantities corresponding to different groups. There are two types of bar charts: `geom_bar()` and `geom_col()`. `geom_bar()` makes the height of the bar proportional to the number of cases in each group (or if the `weight` aesthetic is supplied, the sum of the weights). If you want the heights of the bars to represent values in the data, use `geom_col()` instead. Check the [documentation](https://ggplot2.tidyverse.org/reference/geom_bar.html) for more details.

```

```{block, Dot = 3, part = "Instruction", lang = "python"}
`sns.barplot` - **Bar charts** are useful for comparing quantities corresponding to different groups. Show point estimates and confidence intervals as rectangular bars. Check the [documentation](https://seaborn.pydata.org/generated/seaborn.barplot.html) for more details.

```

```{r, Dot = 3, part = "Code", echo = T, eval = F }
# Draw a set of vertical bars with nested grouping by a two variables
ggplot(data = auto, aes(x = body.style, y = city.mpg)) +
  geom_col(aes(fill = fuel.type))

```

```{python, Dot = 3, part = "Code", echo = T, eval = F }
# Draw a set of vertical bars with nested grouping by a two variables
sns.barplot(x=auto['body-style'], y=auto['city-mpg'], hue=auto['fuel-type'])

```

```{r, Dot = 3, part = "Result", echo = F, eval = T}
# Draw a set of vertical bars with nested grouping by a two variables
ggplot(data = auto, aes(x = body.style, y = city.mpg)) +
  geom_col(aes(fill = fuel.type))

```

```{python, Dot = 3, part = "Result", echo = F, eval = T}
# Draw a set of vertical bars with nested grouping by a two variables
sns.barplot(x=auto['body-style'], y=auto['city-mpg'], hue=auto['fuel-type'])

```


<!-- Dot 4, lang: r, python ------------------------------------------------>

```{block, Dot = 4, part = "Instruction", lang = "r"}
**Heatmaps** can be used to find color-coded patterns in tables of numbers. This section describes how to reorder the correlation matrix according to the correlation coefficient. This is useful to identify the hidden pattern in the matrix. `geom_tile()` uses the center of the tile and its size (`x`, `y`, `width`, `height`).  Check the [documentation](https://ggplot2.tidyverse.org/reference/geom_tile.html) for more details.

```

```{block, Dot = 4, part = "Instruction", lang = "python"}
`sns.heatmap` - **Heatmaps** can be used to find color-coded patterns in tables of numbers. A heat map is a data visualization technique that shows magnitude of a phenomenon as color in two dimensions. The variation in color may be by hue or intensity, giving obvious visual cues to the reader about how the phenomenon is clustered or varies over space.  Check the [documentation](https://seaborn.pydata.org/generated/seaborn.heatmap.html) for more details.

```

```{r, Dot = 4, part = "Code", echo = T, eval = F }
# reshape data
library(reshape2)

# Selecting only numeric columns from a data frame
numeric_cols <- select_if(auto, is.numeric)

# Compute pairwise correlation of columns
corr <- melt(cor(numeric_cols))

# geom_text: insert corresponding cell values in plot
# theme: Rotating and spacing x axis labels
ggplot(data = corr, aes(x = Var1, y = Var2)) +
  geom_tile(aes(fill = value)) +
  geom_text(aes(label = round(value, 1))) +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  )) 

```

```{python, Dot = 4, part = "Code", echo = T, eval = F }
# Compute pairwise correlation of columns
corr = auto.corr()

# annot: Annotate each cell with the numeric value
# linewidths: Add lines between each cell
sns.heatmap(corr, annot=True, linewidths=.1)

```

```{r, Dot = 4, part = "Result", echo = F, eval = T}
# reshape data
library(reshape2)

# Selecting only numeric columns from a data frame
numeric_cols <- select_if(auto, is.numeric)

# Compute pairwise correlation of columns
corr <- melt(cor(numeric_cols))

# geom_text: insert corresponding cell values in plot
# theme: Rotating and spacing x axis labels
ggplot(data = corr, aes(x = Var1, y = Var2)) +
  geom_tile(aes(fill = value)) +
  geom_text(aes(label = round(value, 1))) +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  )) 

```

```{python, Dot = 4, part = "Result", echo = F, eval = T}
# Compute pairwise correlation of columns
corr = auto.corr()

# annot: Annotate each cell with the numeric value
# linewidths: Add lines between each cell
sns.heatmap(corr, annot=True, linewidths=.1)

```


<!-- Dot 5, lang: r, python ------------------------------------------------>

```{block, Dot = 5, part = "Instruction", lang = "r"}
**Scatter plot** is most useful for displaying the relationship between two continuous variables.  It can be used to compare one continuous and one categorical variable, or two categorical variables. The `geom_point()` is used to create scatterplots. A *bubblechart* is a scatterplot with a third variable mapped to the size of points.  Check the [documentation](https://ggplot2.tidyverse.org/reference/geom_point.html) for more details.

```

```{block, Dot = 5, part = "Instruction", lang = "python"}
`sns.scatterplot` - **Scatter plots** show the relationship between two continuous variables; if color-coded, we can also show the relationship with a third [categorical variable](https://en.wikipedia.org/wiki/Categorical_variable). The relationship between `x` and `y` can be shown for different subsets of the data using the `hue`, `size`, and `style` parameters. These parameters control what visual semantics are used to identify the different subsets. Check the [documentation](https://seaborn.pydata.org/generated/seaborn.scatterplot.html) for more details.

```

```{r, Dot = 5, part = "Code", echo = T, eval = F }
# Showing two different grouping variables using "colour" amd "shape" parameter

ggplot(data = auto, aes(x = engine.size, y = wheel.base)) +
  geom_point(aes(
    colour = factor(fuel.type),
    shape = factor(num.of.cylinders)
  ))
  

```

```{python, Dot = 5, part = "Code", echo = T, eval = F }
# Showing two different grouping variables using "hue" amd "style" parameter

sns.scatterplot(data=auto, x='engine-size', y='wheel-base', hue='fuel-type',style='num-of-cylinders')

```

```{r, Dot = 5, part = "Result", echo = F, eval = T}
# Showing two different grouping variables using "colour" amd "shape" parameter

ggplot(data = auto, aes(x = engine.size, y = wheel.base)) +
  geom_point(aes(
    colour = factor(fuel.type),
    shape = factor(num.of.cylinders)
  ))

```

```{python, Dot = 5, part = "Result", echo = F, eval = T}
# Showing two different grouping variables using "hue" amd "style" parameter

sns.scatterplot(data=auto, x='engine-size', y='wheel-base', hue='fuel-type',style='num-of-cylinders')

```


<!-- Dot 6, lang: r, python ------------------------------------------------>

```{block, Dot = 6, part = "Instruction", lang = "r"}
Visualise the distribution of a single continuous variable by dividing the x axis into bins and counting the number of observations in each bin. **Histograms** (`geom_histogram()`) display the counts with bars; frequency polygons (`geom_freqpoly()`) display the counts with lines. Frequency polygons are more suitable when you want to compare the distribution across the levels of a categorical variable. Check the [documentation](https://ggplot2.tidyverse.org/reference/geom_histogram.html) for more details.

```

```{block, Dot = 6, part = "Instruction", lang = "python"}
`sns.distplot` - **Histograms** Plot univariate or bivariate histograms to show distributions of datasets. A histogram is a classic visualization tool that represents the distribution of one or more variables by counting the number of observations that fall within disrete bins.

This function can normalize the statistic computed within each bin to estimate frequency, density or probability mass, and it can add a smooth curve obtained using a kernel density estimate, similar to [`kdeplot()`](https://seaborn.pydata.org/generated/seaborn.kdeplot.html#seaborn.kdeplot). Check the [documentation](https://seaborn.pydata.org/generated/seaborn.histplot.html) for more details.

```

```{r, Dot = 6, part = "Code", echo = T, eval = F }
ggplot(auto, aes(city.mpg)) +
  geom_histogram(
    linetype = "dashed",
    colour = "black",
    fill = "red",
    alpha = 3.0
  )

```

```{python, Dot = 6, part = "Code", echo = T, eval = F }
# kde:If True, smooth the distribution and show as line
sns.histplot(data=auto, x="city-mpg", kde=True)

```

```{r, Dot = 6, part = "Result", echo = F, eval = T}
ggplot(auto, aes(city.mpg)) +
  geom_histogram(
    linetype = "dashed",
    colour = "black",
    fill = "red",
    alpha = 3.0
  )

```

```{python, Dot = 6, part = "Result", echo = F, eval = T}
# kde:If True, smooth the distribution and show as line
sns.histplot(data=auto, x="city-mpg", kde=True)

```






