---
title: "Basic Data structures in Python and R"
description: |
  introducing some basic data structures in Python and R.
author:
  - name: "Parnian Jahangiri Rad"
    occupation: NULL
    affiliation: NULL
    url: NULL
    img: NULL
    lang: python
tech:
  - lang: r
    pkgs: []
  - lang: python
    pkgs: ["pandas"]
date:
  created: "2021-06-23"
  last_updated: "2021-06-23"
categories: ["General"]
applications: ["General"]
cover_image: NULL
slug: "basic-data-structures-in-python-and-r"
output: DataMotto::Dotto
---

```{r DataMotto, echo=F}
DataMotto::use_Dotto()
```

```{r set-up, include=F}
knitr::opts_chunk$set(echo = T,
                      eval = F)
```


<!-- Dot 1, lang: python ------------------------------------------------>

```{block, Dot = 1, part = "Instruction", lang = "python"}
Python. This Dot illustrates how to define a variable , change variable type and 
chaning assignment in Python.
```

```{python, Dot = 1, part = "Code", echo = T, eval = F, }
#variable assignment
x = '300'
print("x is :",x)
print("x class type:",type(x))
#change variable type from str to int
x = int(x)
print("new x class type:",type(x))
#chained assignmen:
n = m = x
print(n,m,x)
print("n=",n," m=",m," x=",x)

```

```{python, Dot = 1, part = "Result", echo = F, eval = T}
#variable assignment
x = '300'
print("x is :",x)
print("x class type:",type(x))
#change variable type from str to int
x = int(x)
print("new x class type:",type(x))
#chained assignmen:
n = m = x
print("n=",n," m=",m," x=",x)
```

<!-- Dot 2, lang: python ------------------------------------------------>

```{block, Dot = 2, part = "Instruction", lang = "python"}
Python. List is a mutable built_in data structure in python that allows us to store 
sets of information in one place.
Lists are one of Python's most powerful features readily accessible to new programmers,
and they tie together many important concepts in programming.

```

```{python, Dot = 2, part = "Code", echo = T, eval = F, }
A=[1,2,"Hi"]
print("last element od list A:",A[-1])
A = [i**2 for i in range(1,5)]
print('new list A is:' , A)
A.insert(2,12)# add 12 at position 2 in list
A.append(4) #add 4 to the end of the list
print("A after adding 12 at position 2 and appending 4:",A)
A.reverse()
print('A after reversing:',A)
print("index of element 16 is :",A.index(16))
A.sort(reverse = True)
print("sorted A descending order:",A)
print("number of element 4 in list A:",A.count(4))
print("A.pop(0) will remove the first element in list A and return it's value:")
A.pop(0)
print("list A after removing it's first element:",A)

```

```{python, Dot = 2, part = "Result", echo = F, eval = T}
A=[1,2,"Hi"]
print("last element of list A:",A[-1])
A = [i**2 for i in range(1,5)]
print('new list A is:' , A)
A.insert(2,12)# add 12 at position 2 in list
A.append(4) #add 4 to the end of the list
print("A after adding 12 at position 2 and appending 4:",A)
A.reverse()
print('A after reversing:',A)
print("index of element 16 is :",A.index(16))
A.sort(reverse = True)
print("sorted A descending order:",A)
print("number of element 4 in list A:",A.count(4))
print("A.pop(0) will remove the first element in list A and return it's value:")
A.pop(0)
print("list A after removing it's first element:",A)

```

```{block, Dot = 3, part = "Instruction", lang = "python"}
Python. Tuple is an ordered collection of objects in Python.
You can't change tuple atfer defining it(unlike list).

```

```{python, Dot = 3, part = "Code", echo = T, eval = F, }
t1 = ("hello",5,4)
print("second elemnt of tuple t1:",t1[1])
try:
  t1[2] = "good"
except TypeError:
  print("'tuple' object does not support item assignment(immutable)")
t2 =  t1 + (6,7,8)
print("t2 is :",t2)
#showing packing and unpacking variables with tuple
print("t2 is : ",t2)
(a,b,c) = (10,11,"apple")
print("a :",a," ,b :",b ," ,c :",c)
a , c = c, a
print("new a :",a," ,new c :",c)

```

```{python, Dot = 3, part = "Result", echo = F, eval = T}
t1 = ("hello",5,4)
print("second elemnt of tuple t1:",t1[1])
try:
  t1[2] = "good"
except TypeError:
  print("'tuple' object does not support item assignment(immutable)")
t2 =  t1 + (6,7,8)
print("t2 is :",t2)
#showing packing and unpacking variables with tuple
print("t2 is : ",t2)
(a,b,c) = (10,11,"apple")
print("a :",a," ,b :",b ," ,c :",c)
a , c = c, a
print("new a :",a," ,new c :",c)

```

<!-- Dot 4, lang: python ------------------------------------------------>

```{block, Dot = 4, part = "Instruction", lang = "python"}
Python. Set is a built_in data structure in Python which is unordered ,
and has no duplicate values.

```

```{python, Dot = 4, part = "Code", echo = T, eval = F, }
A = {1,2,3,3,5,1,2}
print("set A is :",A)
empty_set = set()
A.add(20)
A.remove(3)
print("set A after adding 20 and removing 3:",A)
B = {2,3,5,7,8}
print("(A union B) is:",A|B)
print("A intersection b is: ",A & B)
print("A minus B is:",A - B)
print("symmetric diffrence of A and B:",A ^ B)
if empty_set <= A :
  print("emty set is a subset of A")
else : 
  print("emty set is not a subset of A")
  
```

```{python, Dot = 4, part = "Result", echo = F, eval = T}
A = {1,2,3,3,5,1,2}
print("set A is :",A)
empty_set = set()
A.add(20)
A.remove(3)
print("set A after adding 20 and removing 3:",A)
B = {2,3,5,7,8}
print("(A union B) is:",A|B)
print("A intersection b is: ",A & B)
print("A minus B is:",A - B)
print("symmetric diffrence of A and B:",A ^ B)
if empty_set <= A :
  print("emty set is a subset of A")
else : 
  print("emty set is not a subset of A")
  
```

<!-- Dot 5, lang: python ------------------------------------------------>

```{block, Dot = 5, part = "Instruction", lang = "python"}
Python. Python's dictionaries allow you to connect pieces of related
information.Each piece of information in a dictionary is stored as a key-value pair.
When you provide a key, Python returns the value associated with that key.

```

```{python, Dot = 5, part = "Code", echo = T, eval = F, }
dict1 = {"a":1,"b":2,"c":3} #define a dictionary
print("a is a key and it's value is :",dict1.get("a"))
print("True") if "b" in dict1 else print("False")#search in dictionary
dict1["d"] = 4 #add a new pair to dictionary
dict1["c"] = "10" #modify c's value
del dict1["a"]
print("dict1 after deleting a_1 pair :",dict1)
print("length of dict1 :",len(dict1))
#Looping through all key-value pairs:
for alphabet,number in dict1.items():
  print(alphabet+" : ",number)
#looping through all the keys:
for alphabet in dict1.keys():
  print(alphabet)
#looping through all values:
for number in dict1.keys():
  print(number)
  
```

```{python, Dot = 5, part = "Result", echo = F, eval = T}
dict1 = {"a":1,"b":2,"c":3} #define a dictionary
print("a is a key and it's value is :",dict1.get("a"))
print("True") if "b" in dict1 else print("False")#search in dictionary
dict1["d"] = 4 #add a new pair to dictionary
dict1["c"] = "10" #modify c's value
del dict1["a"]
print("dict1 after deleting a_1 pair :",dict1)
print("length of dict1 :",len(dict1))
#Looping through all key-value pairs:
for alphabet,number in dict1.items():
  print(alphabet+" : ",number)
#looping through all the keys:
for alphabet in dict1.keys():
  print(alphabet)
#looping through all values:
for number in dict1.keys():
  print(number)
  
```
<!-- Dot 6, lang: python ------------------------------------------------>
```{block, Dot = 6, part = "Instruction", lang = "python"}
Puthon. A DataFrame is a table. It contains an array of individual entries, each of which has a certain value. Each entry corresponds to a row (or record) and a column.
Data frame is one of the most commonly used pandas objects.

```

```{python, Dot = 6, part = "Code", echo = T, eval = F, }
import pandas as pd
data_frame1 = pd.DataFrame({"apple" :[3,2,1,4],"orange" :[8,7,8,6],
"lemon":[10,9,11,12]},index=["Joe","John","Matt","Hannah"])
print(data_frame1)
data_frame1.head(2)#rows 1 and 2 of data_frame1
data_frame1.tail(1)
data_frame1.describe()
data_frame1.sort_index()#sort data frame based on indices
data_frame1.sort_values("lemon",ascending = True)
data_frame1[["apple","lemon"]] #choose column
data_frame1[0:2] #choose row
#number of apples and lemons of people with 8 oranges:
data_frame1[data_frame1.orange == 8][["apple","lemon"]]
data_frame1.iloc[1:3,1] #select columns based on column number(column 1)

```

```{python, Dot = 6, part = "Result", echo = F, eval = T}
import pandas as pd
data_frame1 = pd.DataFrame({"apple" :[3,2,1,4],"orange" :[8,7,8,6],
"lemon":[10,9,11,12]},index=["Joe","John","Matt","Hannah"])
print(data_frame1)
data_frame1.head(2)#rows 1 and 2 of data_frame1
data_frame1.tail(1)
data_frame1.describe()
data_frame1.sort_index()#sort data frame based on indices
data_frame1.sort_values("lemon",ascending = True)
data_frame1[["apple","lemon"]] #choose column
data_frame1[0:2] #choose row
#number of apples and lemons of people with 8 oranges :
data_frame1[data_frame1.orange == 8][["apple","lemon"]]
data_frame1.iloc[1:3,1] #select columns based on column number(column 1)

```
