---
title: "Basic data structures in Python"
description: |
  In this Dotto,we will see some of the data structures in python like variable,list,
  tuple,set,dictionary and data frame.
author:
  - name: "Parnian Jahangiri Rad"
    url: "https://example.com/norajones"
# preview: https://www.jfkairport.com/static/JFK/image/jfk_taxi_new.jpg
date: 2021-06-22
tech: [["Python"]]
packages: [Pandas]
categories: [General]
base_url: https://datamotto.com
output: DataMotto::Dotto
preview: "https://bookdown.org/kdonovan125/ibis_data_analysis_r4/_main_files/figure-html/ggplot_ex_4_1-2.png"
---

```{r DataMotto, echo=FALSE}
DataMotto::use_Dotto()
```
<li class="nav-item">
<a class="nav-link dm-dot-title">Report</a>
<div class="dm-dot-content">

Write your `Dotto` Here
<!------Dot1 ,lang = python----------->
```{python, echo = T, out.width="30%"}
#variable assignment
x = '300'
print("x is :",x)
print("class type of x :",type(x))
#change variable type from str to int
x = int(x)
print("new x :",type(x))
#chained assignmen:
n = m = x
print("n:",n," m:",m," x:",x)
```
</div>
</li>

<li class="nav-item">
<a class="nav-link dm-dot-title">Summary</a>
<div class="dm-dot-content">

<!------Dot2 ,lang = python----------->
```{python, echo = T, out.width="30%"}
#List in Python:
lis1 = [1 , 2 , 'hi' , 3.5 , 'bye' ]
print('second and third elements of list lis1 :' , lis1[1:3])
```
```{python, echo = T, out.width="30%"}
lis2 = [i**2 for i in range(1,5)]
print('new list lis2 is:' , lis2)
lis2.insert(2,12)# add 12 at position 2 in list
lis2.append(4) #add 4 to the end of the list
print("new list 2 is :",lis2)
```
``````{python, echo = T, out.width="30%"}
lis2.reverse()
print('lis2 after reversing:',lis2)
```
```{python, echo = T, out.width="30%"}
lis2.index(16)
```
```{python, echo = T, out.width="30%"}
lis2.sort(reverse = True)
print("sorted lis2 in descending order:",lis2)
```

```{python, echo = T, out.width="30%"}
lis2.count(4)
```
```{python, echo = T, out.width="30%"}
lis2.pop(0)
```
```{python, echo = T, out.width="30%"}
print(lis2)
```
</div>
</li>
<!------Dot3,lang = python----------->
```{python, echo = T, out.width="30%"}
#tuple in python:
t1 = ("hello",5,4)
print("1 : second elemnt of tuple t1:",t1[1])
```

```{python, echo = T, out.width="30%"}
#showing that tuple is immutable(unlike list)
try:
  t1[2] = "good"
except TypeError:
  print("2 : tuple' object does not support item assignment(immutable)")
```

```{python, echo = T, out.width="30%"}
t2 =  t1 + (6,7,8)
print("t2 is :",t2)
```

```{python, echo = T, out.width="30%"}
#showing packing and unpacking variables with tuple
print("t2 is : ",t2)
```

```{python, echo = T, out.width="30%"}
(a,b,c) = (10,11,"apple")
print("a :",a," ,b :",b ," ,c :",c)
```

```{python, echo = T, out.width="30%"}
a , c = c, a
print("new a :",a," ,new c :",c)
```
<!------Dot4,lang = python----------->
```{python, echo = T, out.width="30%"}
#set in python:
A = {1,2,3,3,5,1,2}
print("set A is :",A)
```
```{python, echo = T, out.width="30%"}
empty_set = set()
print(empty_set)
print("class type of empty_set:",type(empty_set))
```
```{python, echo = T, out.width="30%"}
A.add(20)
A.remove(3)
print("set A after adding 20 and removing 3:",A)
```
```{python, echo = T, out.width="30%"}
B = {2,3,5,7,8}
print("(A union B) is:",A|B)
```
```{python, echo = T, out.width="30%"}
print("A intersection b is: ",A & B)
```

```{python, echo = T, out.width="30%"}
print("A minus B is:",A - B)
```

```{python, echo = T, out.width="30%"}
print("symmetric diffrence of A and B:",A ^ B)
```

```{python, echo = T, out.width="30%"}
if empty_set <= A :
  print("emty set is a subset of A")
else : 
  print("emty set is not a subset of A")
```
<!------Dot5,lang = python----------->
```{python, echo = T, out.width="30%"}
dict1 = {"a":1,"b":2,"c":3} #define a dictionary
print("a is a key and it's value is :",dict1.get("a"))
```

```{python, echo = T, out.width="30%"}
print("True") if "b" in dict1 else print("False")#search in dictionary
```

```{python, echo = T, out.width="30%"}
dict1["d"] = 4 #add a new pair to dictionary
print(dict1)
```

```{python, echo = T, out.width="30%"}
dict1["c"] = "10" #modify c's value
del dict1["a"]
print("dict1 after deleting a_1 pair :",dict1)
```
```{python, echo = T, out.width="30%"}
print("length of dict1 :",len(dict1))
```
```{python, echo = T, out.width="30%"}
#Looping through all key-value pairs:
for alphabet,number in dict1.items():
  print(alphabet+" : ",number)
```

```{python, echo = T, out.width="30%"}
#looping through all the keys:
for alphabet in dict1.keys():
  print(alphabet)
```
```{python, echo = T, out.width="30%"}
#looping through all values:
for number in dict1.keys():
  print(number)
```
<!------Dot6,lang = python----------->
```{python, echo = T, out.width="30%"}
import pandas as pd
data_frame1 = pd.DataFrame({"apple" :[3,2,1,4],"orange" :[8,7,8,6],
"lemon":[10,9,11,12]},index=["Joe","John","Matt","Hannah"])
print(data_frame1)
```

```{python, echo = T, out.width="30%"}
data_frame1.head(2)#rows 1 and 2 of data_frame1
```
```{python, echo = T, out.width="30%"}
data_frame1.tail(1)
```
```{python, echo = T, out.width="30%"}
data_frame1.describe()
```
```{python, echo = T, out.width="30%"}
data_frame1.sort_index()#sort data frame based on indices
```
```{python, echo = T, out.width="30%"}
data_frame1.sort_values("lemon",ascending = True)
```
```{python, echo = T, out.width="30%"}
data_frame1[["apple","lemon"]] #choose column
```
```{python, echo = T, out.width="30%"}
data_frame1[0:2] #choose row
```
```{python, echo = T, out.width="30%"}
#number of apples and lemons of people with 8 oranges:
data_frame1[data_frame1.orange == 8][["apple","lemon"]]
```
```{python, echo = T, out.width="30%"}
data_frame1.iloc[1:3,1] #select columns based on column number(column 1)
```
