---
title: "`r  paste0(rmarkdown::site_config(input = here::here())$title)`"
description: |
  The main page of Data Motto.
author:
  - name: "Ardalan Mirshani"
    url: "mirshani.com"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: DataMotto::Index
---

```{r index_welcome, echo = F}
htmltools::includeHTML("resources/index_welcome.html")
```

```{r index_github_stars, echo = F}
htmltools::includeHTML("resources/index_github_stars.html")
```

```{r count_dottos, include=FALSE}
configs <- jsonlite::toJSON(config_posts(),
                 auto_unbox = F,
                 pretty = TRUE) %>% jsonlite::fromJSON(flatten = T)

all_techs <- purrr::map(configs, ~ .x$tech) %>% 
  unlist() %>%
  table() %>% 
  data.frame() %>% 
  rename("tech" = ".") %>%
  arrange(desc(Freq))


dotto_vec <- rep(NA, nrow(all_techs))

for(i in 1:length(dotto_vec)){
dotto_vec[i] <- sprintf('
<div class="dottos %s-color">%s <span>%s</span></div>', 
all_techs[i, 'tech'],
tech_html_icon(all_techs[i, 'tech'], full_name = F), 
all_techs[i, 'Freq'])
}

all_dottos <- paste0(dotto_vec, collapse = "")
```


```{r index_dottos, echo=F, results='asis'}
htmltools::HTML(sprintf('
<section id="dm-middle" class="pt-5 pb-5">
<div class="container">
<h2>OUR DOTTOS</h2>
<div class="pt-5 row justify-content-center">
%s
</div>
</div>
</section>
', all_dottos))
```

<!-- Section Our Dottos ------------------------>

```{r index_cards, echo = F}
htmltools::includeHTML("resources/index_cards.html")
```
