---
title: "Finland"
description: |
  The World Happiness dataset contains six factors to measure global happiness: life expectancy, economics, social support, absence of corruption, freedom, and generosity. These factors were reported for 166 countries around the world from 2005 to 2020. In this Dotto, we want to find the top five happiest countries then plot the happiness rate for these countries from 2015 to 2019.
  
author:
  - name: "Mahyar Sharifi"
    occupation: "Internship"
    affiliation: "DataMotto"
    url: "https://www.linkedin.com/in/mahyar-sharifi-06126616a"
    img: NULL
    lang: ["python", "r"]
  - name: "Mahyar Sharifi"
    occupation: "Internship"
    affiliation: "DataMotto"
    url: NULL
    img: NULL
    lang: "python"
tech:
  - lang: r
    pkgs: ["dplyr", "ggplot2"]
  - lang: python
    pkgs: ["pandas", "seaborn"]
date:
  created: "2021-06-29"
  last_updated: "2021-06-29"
categories: "Storyteller"
applications: "Governance"
cover_image: NULL
slug: "finland"
output: DataMotto::Dotto
---

```{r DataMotto, echo=FALSE}
DataMotto::use_Dotto()
```

<!-- Dot 1, lang: r ------------------------------------------------>

```{block, Dot = 1, part = "Instruction", lang = "r"}
In the first DOT, we import two packages: pandas: importing and wrangling dataset seaborn: plotting a line-plot Then we import the World Happiness dataset and select rows for 2015 to 2019 for all countries.

```

```{block, Dot = 1, part = "Instruction", lang = "python"}
In the first DOT, we import two packages: pandas: importing and wrangling dataset seaborn: plotting a line-plot Then we import the World Happiness dataset  and select rows for 2015 to 2019 for all countries.

```


```{r, Dot = 1, part = "Code", echo = T, eval = F}
#load library
library(dplyr)
library(ggplot2)

#read world happiness dataset
data <- read.csv('Dataset/world-happiness-report.csv', fileEncoding="UTF-8-BOM")
head(data)

# Select Dataset from 2015-2019
data <- filter(data,year %in% c(2015:2019))

```

```{r, Dot = 1, part = "Result", echo = F, eval = T}
#load library
library(dplyr)
library(ggplot2)

#read world happiness dataset
data <- read.csv('Dataset/world-happiness-report.csv', fileEncoding="UTF-8-BOM")
head(data)

# Select Dataset from 2015-2019
data <- filter(data,year %in% c(2015:2019))


```

```{python, Dot = 1, part = "Code", echo = T, eval = F}
#Import Packages
import pandas as pd
import seaborn as sns

#read world happiness dataset
data = pd.read_csv('Dataset/world-happiness-report.csv')
data.shape

# Select Dataset from 2015-2019
data = data[data['year'].isin(range(2015,2020))]

```

```{python, Dot = 1, part = "Result", echo = F, eval = T}
#Import Packages
import pandas as pd
import seaborn as sns

#read world happiness dataset
data = pd.read_csv('Dataset/world-happiness-report.csv')
data.shape

# Select Dataset from 2015-2019
data = data[data['year'].isin(range(2015, 2020))]

```

```{block, Dot = 2, part = "Instruction", lang = "r"}
After we select the dataset, the average of Life Ladder calculates for each country. Then the top five happiest countries will be identified by sorting the dataset by Life Ladder columns.

```

```{block, Dot = 2, part = "Instruction", lang = "python"}
After we select the dataset, the average of Life Ladder calculates for each country. Then the top five happiest countries will be identified by sorting the dataset by Life Ladder columns.

```

```{r, Dot = 2, part = "Code", echo = T, eval = F}
# Grouping Data by Country
data_grouped_country <- group_by(data, Country.name)
data_grouped_country <- summarise(data_grouped_country, Mean.Life.Ladder = mean(Life.Ladder))

# Sort the New data_grouped_country by Life Ladder column
happiest_country <- arrange(data_grouped_country, desc(Mean.Life.Ladder))
head(happiest_country, 8)

#Identify and select five-top country
as.vector(t(happiest_country[1:5,1]))

```

```{r, Dot = 2, part = "Result", echo = F, eval = T}
# Grouping Data by Country
data_grouped_country <- group_by(data, Country.name)
data_grouped_country <- summarise(data_grouped_country, Mean.Life.Ladder = mean(Life.Ladder))

# Sort the New Dataset by Life Ladder column
happiest_country <- arrange(data_grouped_country, desc(Mean.Life.Ladder))
head(happiest_country, 8)

as.vector(t(happiest_country[1:5,1]))

```

```{python, Dot = 2, part = "Code", echo = T, eval = F}
#Calculate Mean of Life Ladder for Each Country during 2015-2019
data_grouped = data.groupby('Country name').mean()
data_grouped

#Sort data_grouped by Life Ladder Column
sorted_data = data_grouped.sort_values(['Life Ladder'],
          ascending = False)

```

```{python, Dot = 2, part = "Result", echo = F, eval = T}
#Calculate Mean of Life Ladder for Each Country during 2015-2019
data_grouped = data.groupby('Country name').mean()
data_grouped

#Sort data_grouped by Life Ladder Column
sorted_data = data_grouped.sort_values(['Life Ladder'],
          ascending = False)


```

```{block, Dot = 3, part = "Instruction", lang = "r"}
Finland, Denmark, Switzerland, Norway, and Iceland were identified as the happiest country in a row from 2015 to 2019. In this Dot, the new dataset will create for these countries which name is "top-five". As we can see in the top-five dataset, Iceland has no information for 2018.

```

```{block, Dot = 3, part = "Instruction", lang = "python"}
Finland, Denmark, Switzerland, Norway, and Iceland were identified as the happiest country in a row from 2015 to 2019. In this Dot, the new dataset will create for these countries which name is "top-five". As we can see in the top-five dataset, Iceland has no information for 2018.

```

```{r, Dot = 3, part = "Code", echo = T, eval = F}
# Select New Dataset for the Top-five Happiest Country
data_top_five = filter(data, Country.name %in% 
                         as.vector(t(happiest_country[1:5,1])))
head(data_top_five, 50)

```

```{r, Dot = 3, part = "Result", echo = F, eval = T}
# Select New Dataset for the Top-five Happiest Country
data_top_five = filter(data, Country.name %in% 
                         as.vector(t(happiest_country[1:5,1])))
head(data_top_five, 50)

```

```{python, Dot = 3, part = "Code", echo = T, eval = F}
# Select New Dataset for the Top-five Happiest Country
data_top_five = data[(data['Country name'].isin(sorted_data.index[:5]))]

```

```{python, Dot = 3, part = "Result", echo = F, eval = T}
# Select New Dataset for the Top-five Happiest Country
data_top_five = data[(data['Country name'].isin(sorted_data.index[:5]))]

```

```{block, Dot = 4, part = "Instruction", lang = "r"}
The final Dot is to plot the trend of Life Ladder from 2015 to 2019. 
The line plot shows that Finland has been increasing considerably and reached its peak in 2018.
For Switzerland and Denmark, we can see an increasing trend like Finland. On the other hand,  Iceland has a slight fluctuation, and  Norway has a decreasing trend in this period.

```

```{block, Dot = 4, part = "Instruction", lang = "python"}
The final Dot is to plot the trend of Life Ladder from 2015 to 2019. 
The line plot shows that Finland has been increasing considerably and reached its peak in 2018.
For Switzerland and Denmark, we can see an increasing trend like Finland. On the other hand,  Iceland has a slight fluctuation, and  Norway has a decreasing trend in this period.

```

```{r, Dot = 4, part = "Code", echo = T, eval = F}
# Plot a catplot for the top-5 Happiest Country
ggplot(data = data_top_five,
       mapping = aes(x = year, y=Life.Ladder, 
                     color=Country.name))+
  geom_point(mapping = aes(),size=3)+
  geom_line(mapping = aes())+
  geom_path(size = 0.9)

```

```{r, Dot = 4, part = "Result", echo = F, eval = T}
# Plot a catplot for the top-5 Happiest Country
ggplot(data = data_top_five,
       mapping = aes(x = year, y=Life.Ladder, 
                     color=Country.name))+
  geom_point(mapping = aes(),size=3)+
  geom_line(mapping = aes())+
  geom_path(size = 0.9)

# Plot a catplot for the top-5 Happiest Country
ggplot(data = data_top_five,
       mapping = aes(x = year, y=Life.Ladder, 
                     color=Country.name))+
  geom_point(mapping = aes(),size=3)+
  geom_line(mapping = aes())+
  geom_path(size = 0.9)

```

```{python, Dot = 4, part = "Code", echo = T, eval = F}
# Plot a catplot for the top-5 Happiest Country
sns.catplot(data = data_top_five , x ='year',y = 'Life Ladder' , hue ='Country name' , kind = 'point')

```

```{python, Dot = 4, part = "Result", echo = F, eval = T}
# Plot a catplot for the top-5 Happiest Country
sns.catplot(data = data_top_five , x ='year',y = 'Life Ladder' , hue = 'Country name' , kind = 'point')

```
