---
title: "Post Template"
description: |
  Here is a .html template for Dotto!
author: Pedram
date: 01-26-2021
# output:
#   html_fragment
output:
  # html_document
  distill::distill_article:
    self_contained: false
  #   theme: null
 #   highlight: null
  #   highlight_downlit: false
#   #  css: ../../resources/css/style.css
#     includes:
#       before_body: ../../resources/post.html
---

```{css, echo = F}

[role=banner] {
  display: none;
}

d-title, d-byline {
  display: none;
}

# d-article {
#   display: none;
# }

d-appendix {
  margin-top: -10px;
}

.article-footer {
  text-align: center;
}

```

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />


```{r, echo=F}
#htmltools::includeScript(here::here("inst","dotto","dotto.js"))
```


```{r, echo=F}
devtools::load_all()
#htmltools::includeCSS(here::here("inst","dotto","dotto.css"))
dotto()
```

<div class="l-screen">
<section id="dm-post-header">
<div class="container">
<header id="dm-header" class="pt-3 pb-2 clearfix">
<div id="dm-logo" class="float-left">
<div class="dm-logo-dot"></div>
<div class="dm-logo-dot"></div>
<div class="dm-logo-dot"></div>
<span>DATA MOTTO</span>
</div>
<nav class="float-left pl-5 pt-2" id="dm-nav">
<ul class="row">
<li class="d-inline-block"><a href="#">HOME</a></li>
<li class="d-inline-block pl-4"><a href="#">THE WHOLE GAME!</a></li>
<li class="d-inline-block pl-4"><a href="#">BLOG</a></li>
<li class="d-inline-block pl-4"><a href="#">ABOUT</a></li>
</ul>

<div class="dropdown" id="dm-mo-nav">
<button type="button" class="btn gradient-button text-white rounded-pill dropdown-toggle" data-toggle="dropdown">
<i class="fa fa-bars" aria-hidden="true"></i>
</button>
<div class="dropdown-menu" id="dm-mobile-content">
<a class="dropdown-item" href="#">HOME</a>
<a class="dropdown-item" href="#">THE WHOLE GAME!</a>
<a class="dropdown-item" href="#">BLOG</a>
<a class="dropdown-item" href="#">ABOUT</a>
</div>
</div>
</nav>
<button class="float-right btn gradient-button text-white rounded-pill" id="get-started">GET STARTED</button>

</header>
</div>
</section>


<section id="dm-post" class="pt-4">
<div class="container">
<div class="row">

<div id="dotto" class="col-md-1 pr-md-0 pl-md-0">
<ul class="hasDotto">
<li class="dotto-active" data-id="1">
<div class="dm-rep">
<div class="dm-rep-btn" data-post-id="1"><i class="fas fa-caret-up"></i></div>
<div class="dm-rep-btn-loading spin"><i class="fas fa-circle-notch"></i></div>
</div>
<div class="total-likes" data-post-id="1">0</div>
<div class="dotto-dots click-dots" data-toggle="tooltip" data-placement="top" title="Test Title"></div>
</li>

</ul>
</div>

<div id="dotto-content" class="col-md-11 pr-md-0 pl-md-0">
<div class="dotto-container" style="display: block;" data-id="1">
<div id="dm-desc">
<div class="row">
<div class="col-md-6">
<h2>New York Taxi fare rate</h2>
<p>A short description of the post.</p>
</div>
<div class="col-md-4">
<div id="dm-techs">
<i class="fab fa-python"></i>
</div>
<div id="dm-tags" class="pt-2">
<span class="badge badge-pill badge-info">Visualization</span>
</div>

</div>
<div class="col-md-2">
<div class="dm-posts-desc">
<span class="pr-1"><i class="far fa-clock"></i> Jan. 3, 2021</li>
<br/>
<span><i class="far fa-user"></i> Ardalan Mirshani</li>
</div>
</div>
</div>
</div>

<ul class="nav nav-tabs">
<li class="nav-item">
<a class="nav-link active dm-dot-title">Intro</a>
<div class="dm-dot-content active">
Intro
</div>
</li>
<li class="nav-item">
<a class="nav-link dm-dot-title">Data</a>
<div class="dm-dot-content">
Data
</div>
</li>
<li class="nav-item">
<a class="nav-link dm-dot-title">Cleaning</a>
<div class="dm-dot-content">
Cleaning
</div>
</li>
<li class="nav-item">
<a class="nav-link dm-dot-title">Visulization</a>
<div class="dm-dot-content">
Visulization
</div>
</li>
</ul>
</div>
</div>

</div>
</div>
</section>

<footer id="dm-footer" class="pt-3 pb-3">
<div class="container">
<div id="dm-social" class="text-center">
<a href="https://twitter.com/DataMotto" class="fab fa-twitter"></a>
<a href="https://www.linkedin.com/company/datamotto" class="fab fa-linkedin"></a>
<a href="https://Datamotto.slack.com" class="fab fa-slack"></a>
</div>
<div id="dm-copy" class="text-center mt-3">copyright <i class="fas fa-copyright"></i> 2021</div>
</div>
</footer>
</div>

