#' Create a `Dotto` family be generating a new `Dotto` based on another existing `Dotto`.
#'
#' @description It creates a template of `Dotto` based on an existing `Dotto` and we call them a family.
#'   The new `Dotto` automatically has a line connection to the base `Dotto` and the card generated in
#'   the index page combine the information related to all family.
#'
#' @param Dotto_base_label The label (or path) of the `Dotto`'s folder whom we want to make a family with. This can
#'   be the Dotto's label ( e.g., `D001`) or the full address
#'   (e.g., `path/to/D001-2020-11-21-foo`).
#' @param open If open the dotto file in Rstudio or not. Default is `TRUE`.
#' @importFrom here here
#' @importFrom glue glue
#' @export
create_family <- function(Dotto_base_label, lang = NULL, open = T) {

  lang <- resolve_lang(lang)

  all_rmds <- list.files(here::here("posts/Dotto"),
                         all.files = T, full.names = T,
                         recursive = T, pattern = "\\.Rmd$")

  all_folders <- all_rmds %>%
    dirname() %>%
    basename()

  Dotto_base_dir_name <- stringr::str_subset(all_folders, pattern = paste0("^", Dotto_base_label))
  if(length(Dotto_base_dir_name) == 0){
    Dotto_base_dir <- stringr::str_subset(all_rmds %>% dirname(), pattern = Dotto_base_label)
    if(length(Dotto_base_dir) == 0){
      stop("There is no Dotto with the label/path.")
    } else {

    }
  } else {
    Dotto_base_dir <- stringr::str_subset(all_rmds %>% dirname(), Dotto_base_dir_name)
  }

  Dotto_base_rmd <- list.files(Dotto_base_dir, full.names = T, pattern = "\\.Rmd$")

  # -----
  Dotto_yml_base <- rmarkdown::yaml_front_matter(Dotto_base_rmd)
  Dotto_idyml_base <- yaml::read_yaml(paste0(Dotto_base_dir,"/.yml"))
# ---------------------------

  post_parent <- here::here("posts/Dotto")
  date_prefix <- format(Sys.Date(), "%Y-%m-%d")
  slug <- create_slug(title = Dotto_yml_base$title, slug = Dotto_yml_base$slug)
  dotto_number <- list.files(here::here("posts/Dotto"), full.names = F) %>% length() + 1
  dotto_label <- paste0("D", stringr::str_pad(3, string = dotto_number, pad = "0"))
  dotto_folder_name <- paste0(dotto_label, "-", date_prefix, "-", slug, "-", lang)
  dotto_file_name <- paste0(slug, "-", lang, ".Rmd")
  dotto_path <- glue::glue("{post_parent}/{dotto_folder_name}/{dotto_file_name}")

  create_path_if_not_exist(glue::glue("{post_parent}/{dotto_folder_name}"))
  #create_file_if_not_exist(dotto_path)

# create .yml id ---------------------
yml_id_path <- glue::glue("{post_parent}/{dotto_folder_name}/.yml")

  dotto_id <- uuid::UUIDgenerate(use.time = T)
  family_id <- Dotto_idyml_base$family_id
  line_ids <- family_id

  res <- T
  if(file.exists(yml_id_path)){
    res <- YN("Uniq id is already exists, override?")
  }
  if(res) {
    con <- file(yml_id_path, open = "w", encoding = "UTF-8")
    xfun::write_utf8(sprintf(
'# !!! This file is read-only and automatically generated by DataMotto.
# !!! Do not change anything manually!
dotto_number: %s
dotto_label: "%s"
dotto_id: "%s"
family_id: "%s"
# ------------------
dotto_label_base_in_family: "%s"
dotto_id_base_in_family: "%s"
# ------------------
line_ids: ["%s"]
',
dotto_number,
dotto_label,
dotto_id,
family_id,
Dotto_idyml_base$dotto_label_base_in_family,
Dotto_idyml_base$dotto_id_base_in_family,
Dotto_idyml_base$line_ids
), con)
close(con)
}
  usethis::ui_done(glue::glue("New id with a connection to Dotto {Dotto_idyml_base$dotto_label} is created."))
  # create Rmd file ----------
  ind_yaml <- readLines(Dotto_base_rmd) %>%
    stringr::str_which(pattern = "^---")

  ind_yam_end <- ind_yaml[2]

  Dotto_body_base <- readLines(Dotto_base_rmd)[-(1:ind_yam_end)]

  Dotto_yaml_new <- sprintf(
'---
title: "%s"
description: |
  %s
author:
  - name: "First Last"
    occupation: NULL
    affiliation: NULL
    url: NULL
date: "%s"
techs:
  - lang: "%s"              # "r" "python" "julia" "sql" ...
    pkg: NULL
categories: %s
applications: %s            # ["Finance", "Pharma"]
cover_image: "%s"
slug: "%s"
output: DataMotto::Dotto
---',
Dotto_yml_base$title %>% if_null_return_stringnull(),
Dotto_yml_base$description %>%
  if_null_return_stringnull() %>%
  stringr::str_remove(pattern = "\\\n$"),
date_prefix,
lang %>% if_null_return_stringnull(),
Dotto_yml_base$categories %>%
  if_null_return_stringnull() %>%
  convert_vec_to_ymlform(),
Dotto_yml_base$applications %>%
  if_null_return_stringnull() %>%
  convert_vec_to_ymlform(),
Dotto_yml_base$cover_image %>% if_null_return_stringnull(),
Dotto_yml_base$slug %>% if_null_return_stringnull()
)


  con <- file(dotto_path, open = "w", encoding = "UTF-8")
  xfun::write_utf8(Dotto_yaml_new, con)
  xfun::write_utf8(Dotto_body_base, con)
  close(con)

  open_file(dotto_path, open = open)

  setwd(dirname(dotto_path))
  usethis::ui_done(cli::col_cyan(glue::glue("Set working directory into {dirname(dotto_path)}")))

  return(invisible(NULL))

  # -----------------------


}



# If NULL, returns a NULL string
if_null_return_stringnull <- function(text) {
  if(is.null(text)){
    return("NULL")
  } else {
    return(text)
  }
}

# Convert vector to yaml format
convert_vec_to_ymlform <- function(vec){
  if(length(vec) == 1){
    return(paste0("\"", vec %>% as.character(), "\""))
  } else {
    vec <- purrr::map_chr(vec, ~ paste0("\"", .x, "\""))
    return(paste0("[", paste0(vec, collapse = ", "), "]"))
  }
}
