#' Create a new Dotto
#'
#' @description It creates a dotto (.Rmd) based on a default `slug`, created automatically based on title.
#'
#' @details In the `yml` section, here is the avaialbe values for some tags:
#'   - `lang`: `R`, `python`, `julia`, `sql`, `bash`, `js`, `node`, `d3`, `Rcpp`, `stan`
#'   - `categories`: `Importing-Cleaning`, `Manipulation`, `Visualization`, `Machine-Learning`, `Statistical-Learning`, `Reporting`, `Data-Engineering`
#'   - `url`: A personal url address that can be for: your persoanl website, twitter account, linkedin, etc.
#'   - `applications`: Having an specific applications on files `Finance`, `Pharma`.
#'
#' @param title Title of the dotto post.
#' @param lang The programming language for writing the Dotto. Default is `R`. Other
#'   options are `python`, `julia`, `sql`, `bash`, `js`, `node`, `d3`, `Rcpp`, `stan`. It is not
#'   case-sensitive.
#' @param open If open the dotto file in Rstudio or not. Default is `TRUE`.
#' @importFrom here here
#' @importFrom glue glue
#' @export
create_Dotto <- function(title = NULL, lang = "r", open = T) {

  if(is.null(title)){
    stop('\n argument "title" is missing, with no default')
  }

  lang <- resolve_lang(lang)
  if(is.null(lang)){
    return(invisible(NULL))
  }
  post_parent <- here::here("posts/Dotto")
  date_prefix <- format(Sys.Date(), "%Y-%m-%d")
  slug <- create_slug(title = title, slug = NULL)
  dotto_number <- list.files(here::here("posts/Dotto"), full.names = F) %>% length() + 1
  dotto_label <- paste0("D", stringr::str_pad(3, string = dotto_number, pad = "0"))
  dotto_folder_name <- paste0(dotto_label, "-", date_prefix, "-", slug, "-", lang)
  dotto_file_name <- paste0(slug, "-", lang, ".Rmd")
  dotto_path <- glue::glue("{post_parent}/{dotto_folder_name}/{dotto_file_name}")

  create_path_if_not_exist(glue::glue("{post_parent}/{dotto_folder_name}"))
  create_file_if_not_exist(dotto_path)

# create .yml id ---------------------
  yml_id_path <- glue::glue("{post_parent}/{dotto_folder_name}/.yml")

  dotto_id <- uuid::UUIDgenerate(use.time = T)
  family_id <- uuid::UUIDgenerate(use.time = T)
  line_ids <- family_id

  res <- T
  if(file.exists(yml_id_path)){
    res <- YN("Uniq id is already exists, override?")
  }
  if(res) {
    con <- file(yml_id_path, open = "w", encoding = "UTF-8")
    xfun::write_utf8(sprintf(
'# !!! This file is read-only and automatically generated by DataMotto.
# !!! Do not change anything manually!
dotto_number: %s
dotto_label: "%s"
dotto_id: "%s"
family_id: "%s"
# ------------------
dotto_label_base_in_family: "%s"
dotto_id_base_in_family: "%s"
# ------------------
line_ids: ["%s"]
',
dotto_number,
dotto_label,
dotto_id,
family_id,
dotto_label,
family_id,
line_ids
), con)
close(con)
}

# yaml --------------------------
yaml <- sprintf(
'---
title: "%s"
description: |
  A short description of the Dotto.
author:
  - name: "First Last"
    occupation: NULL
    affiliation: NULL
    url: NULL
date: "%s"
techs:
  - lang: "%s"               # "r" "python" "julia" "sql" ...
    pkg: NULL
categories: "Manipulation"  # ["Importing-Cleaning", ... ]
applications: NULL          # ["Finance", "Pharma"]
cover_image:
slug: "%s"
output: DataMotto::Dotto
---', title, date_prefix, lang, slug)

# body ---------------
body <-
sprintf(
'
```{r DataMotto, echo=FALSE}
DataMotto::use_Dotto(rmarkdown::metadata)
```

```{r set-up, include=F}
knitr::opts_chunk$set(echo = T,
                      eval = T)
library(htmltools)
```

<!-- Dot 1 ------------------------------------------------>

```{r, Dot1-intro, echo = F, Dot_title = "Intro", Dot_active = TRUE}
h1("Description:")
"Here is a sample for your description and details."
```
<!-- Dot 2 ------------------------------------------------>

```{r, Dot2-highlight, eval = F, Dot_title = "Highlight"}
h1("Highligh:")
ggplot +
geom_point +
scale for coloring
```
<!-- Dot 3 ------------------------------------------------>

```{r, Dot3-desc, Dot_title = "Title", Dot_open = T, Dot_close = F}
h1("Dot description:")
```

```{%s, Dot3-code, Dot_open = F, Dot_close = T}
plot(cars)
```

', lang, lang)

con <- file(dotto_path, open = "w", encoding = "UTF-8")
on.exit(close(con), add = TRUE)
xfun::write_utf8(yaml, con)
xfun::write_utf8(body, con)

open_file(dotto_path, open = open)

setwd(dirname(dotto_path))
usethis::ui_done(cli::col_cyan(glue::glue("Set working directory into {dirname(dotto_path)}")))

return(invisible(NULL))

}




#' Convert a technology language to valid engine name
#' @noRd
resolve_lang <- function(lang) {
  default_engines <- c("R", "python", "julia", "sql", "bash", "js", "node", "d3", "Rcpp", "stan")
  selected_ind <- stringr::str_detect(string = tolower(default_engines), pattern = paste0("\\b",tolower(lang),"\\b"))
  if(sum(selected_ind)!=0){
    return(default_engines[selected_ind] %>% as.character())
  } else {
    usethis::ui_oops(paste0("There is no supported engine for ", lang))
    usethis::ui_code(paste("List of supported languages:",
                           paste0(default_engines, collapse = ", ")))
    return(NULL)
  }

}
